version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - 8090:8090
      - 3306:3306
    volumes:
      - /var/lib/docker/volumes/mysql:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8090/healthcheck"]
    #   timeout: 20s
    #   retries: 100
